# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vpoly\qt\design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Matrix(object):
    def setupUi(self, Matrix):
        Matrix.setObjectName("Matrix")
        Matrix.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Matrix)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rows = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(13)
        self.rows.setFont(font)
        self.rows.setObjectName("rows")
        self.verticalLayout_2.addWidget(self.rows)
        self.columns = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(13)
        self.columns.setFont(font)
        self.columns.setObjectName("columns")
        self.verticalLayout_2.addWidget(self.columns)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.columnNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.columnNumber.setObjectName("columnNumber")
        self.horizontalLayout_3.addWidget(self.columnNumber)
        self.showMinimum = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.showMinimum.setFont(font)
        self.showMinimum.setObjectName("showMinimum")
        self.horizontalLayout_3.addWidget(self.showMinimum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rowNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.rowNumber.setObjectName("rowNumber")
        self.horizontalLayout_2.addWidget(self.rowNumber)
        self.sumRow = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.sumRow.setFont(font)
        self.sumRow.setObjectName("sumRow")
        self.horizontalLayout_2.addWidget(self.sumRow)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.sumAll = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.sumAll.setFont(font)
        self.sumAll.setObjectName("sumAll")
        self.verticalLayout_3.addWidget(self.sumAll)
        self.randomiseMatrix = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(12)
        self.randomiseMatrix.setFont(font)
        self.randomiseMatrix.setObjectName("randomiseMatrix")
        self.verticalLayout_3.addWidget(self.randomiseMatrix)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Matrix.setCentralWidget(self.centralwidget)

        self.retranslateUi(Matrix)
        QtCore.QMetaObject.connectSlotsByName(Matrix)

    def retranslateUi(self, Matrix):
        _translate = QtCore.QCoreApplication.translate
        Matrix.setWindowTitle(_translate("Matrix", "MainWindow"))
        self.pushButton_2.setText(_translate("Matrix", "Confirm"))
        self.showMinimum.setText(_translate("Matrix", "Minimum in Column"))
        self.sumRow.setText(_translate("Matrix", "Sum of Row"))
        self.sumAll.setText(_translate("Matrix", "Sum of All"))
        self.randomiseMatrix.setText(_translate("Matrix", "Randomise"))
